<?php
/**
 * verify_notice.php — "Check your email" page shown right after registration.
 *
 * WHY THIS DESIGN: InfinityFree blocks all outbound email/HTTP from the
 * server, so the server itself cannot send emails. Instead, the email is
 * sent from the USER'S BROWSER via EmailJS (free tier: 200 emails/month).
 *
 * The SECURITY-CRITICAL parts all stay server-side:
 *   - the verification token is generated by PHP (random 32 bytes),
 *   - the token is stored in the database,
 *   - the activation link is validated by verify_email.php on the server.
 * The browser's only job is delivering the email containing the link.
 *
 * ONE-TIME SETUP (see README-EMAIL.txt in this zip):
 *   1. Create a free account at https://www.emailjs.com
 *   2. Add your Gmail as an Email Service → copy the Service ID
 *   3. Create an email Template (variables used: to_name, to_email,
 *      verification_link) → copy the Template ID
 *   4. Account → General → copy your Public Key
 *   5. Fill the three constants below.
 */

// ── EMAILJS CONFIG — FILL THESE IN ────────────────────────────────
const EMAILJS_PUBLIC_KEY  = 'YOUR_PUBLIC_KEY';
const EMAILJS_SERVICE_ID  = 'YOUR_SERVICE_ID';
const EMAILJS_TEMPLATE_ID = 'YOUR_TEMPLATE_ID';

require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/functions.php';

// Session must have a pending verification (set by register.php / login.php)
$pending = $_SESSION['pending_verification'] ?? null;
if (!$pending || empty($pending['email']) || empty($pending['token'])) {
    redirect('/thalassemia/auth/login.php');
}

// Build the absolute verification link (works on http and https hosts)
$scheme = (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) ? $_SERVER['HTTP_X_FORWARDED_PROTO']
          : (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http'));
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$verifyLink = $scheme . '://' . $host . '/thalassemia/auth/verify_email.php?token=' . rawurlencode($pending['token']);

$pageTitle = 'Verify Your Email';
require __DIR__ . '/../includes/header.php';
?>

<div class="auth-card">
  <div class="auth-logo">
    <span class="auth-logo-icon heartbeat">
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 2.5 C12 2.5, 19 9, 19 14 C19 17.5, 16 20, 12 20 C8 20, 5 17.5, 5 14 C5 9, 12 2.5, 12 2.5Z"/>
        <path d="M8 14 Q12 11, 16 14" stroke-width="1.5"/>
      </svg>
    </span>
    <span class="auth-logo-text">Rakt<span class="accent">Sethu</span></span>
  </div>
  <p class="auth-subtitle">Verify Your Email</p>
  <p class="auth-tagline">One last step to activate your account</p>

  <div class="flash flash-success" style="margin-bottom:14px;">
    Account created for <strong><?= h($pending['email']) ?></strong> — now confirm it's really your email.
  </div>

  <p class="muted" style="font-size:0.85rem;margin-bottom:16px;">
    Click the button below and we'll send a verification link to your inbox.
    Open the email and click the link to activate your account.
  </p>

  <button type="button" class="btn-primary" id="sendEmailBtn" style="width:100%;">
    ✉️ Send Verification Email
  </button>

  <p id="sendStatus" class="muted" style="font-size:0.8rem;margin-top:12px;text-align:center;"></p>

  <p class="muted" style="font-size:0.75rem;margin-top:18px;">
    Didn't get the email? Check your spam folder, then press the button again.
  </p>

  <a href="/thalassemia/auth/verify_email.php?token=<?= rawurlencode($pending['token']) ?>"
     class="admin-login-link" style="display:block;margin-top:8px;">
    Already clicked the link in your email? Continue →
  </a>
</div>

<script src="https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js"></script>
<script>
(function () {
  // Filled from the PHP constants above
  var PUBLIC_KEY  = <?= json_encode(EMAILJS_PUBLIC_KEY) ?>;
  var SERVICE_ID  = <?= json_encode(EMAILJS_SERVICE_ID) ?>;
  var TEMPLATE_ID = <?= json_encode(EMAILJS_TEMPLATE_ID) ?>;

  var btn    = document.getElementById('sendEmailBtn');
  var status = document.getElementById('sendStatus');

  function sendVerification() {
    if (PUBLIC_KEY.indexOf('YOUR_') === 0) {
      status.textContent = 'Email sending is not configured yet — see README-EMAIL.txt.';
      status.style.color = '#b45309';
      return;
    }
    btn.disabled = true;
    btn.textContent = 'Sending…';
    status.textContent = '';
    emailjs.init({ publicKey: PUBLIC_KEY });
    emailjs.send(SERVICE_ID, TEMPLATE_ID, {
      to_name:            <?= json_encode($pending['name'] ?? 'there') ?>,
      to_email:           <?= json_encode($pending['email']) ?>,
      verification_link:  <?= json_encode($verifyLink) ?>,
      subject:            'Verify your RaktSethu account'
    }).then(function () {
      btn.disabled = false;
      btn.textContent = '✉️ Resend Verification Email';
      status.textContent = '✓ Email sent! Check your inbox (and spam folder).';
      status.style.color = '#059669';
    }).catch(function (err) {
      btn.disabled = false;
      btn.textContent = '✉️ Try Sending Again';
      status.textContent = 'Could not send the email (' + (err && err.status ? 'error ' + err.status : 'network error') + '). Press try again.';
      status.style.color = '#b91c1c';
    });
  }

  btn.addEventListener('click', sendVerification);
})();
</script>

<?php require __DIR__ . '/../includes/footer.php'; ?>
